### ISSUE TITLE
Error "implicit argument passing of super from method defined by define_method() is not supported." when using jenkins_slave

### ISSUE THREAD

**Issue by jmaass** [sous-chefs/jenkins#524]
### Cookbook version

3.1.0
### Chef-client version

12.14.89
### Platform Details

CentOS 7 64-Bit, 3.10.0-327.28.3.el7.x86_64
### Scenario:

Trying to set up a Jenkins JNLP slave with authentication in a wrapper cookbook that uses the jenkins community cookbook.
### Steps to Reproduce:

```
#
# Cookbook Name:: mnet_jenkins
# Recipe:: slave
#
# Copyright (C) 2016 M-net Telekommunikations GmbH
#
# All rights reserved - Do Not Redistribute
#

include_recipe 'role_default'
include_recipe 'chef-vault'

#
# Install the right Java
#
include_recipe 'java'

#
# Define some variables we need
#
master = node['jenkins']['master']['host']
ipaddress = node['ipaddress']
auth_user = node['mnet_jenkins']['auth_user']
jenkins_keys = chef_vault_item('mnet_jenkins', 'keys')

#
# Create the Jenkins OS group
#
group 'jenkins' do
  append  true
  gid     <you wish>
  action  :create
end

#
# Create the jenkins OS User
#
user 'jenkins' do
  comment     'Jenkins Slave'
  home        '/home/jenkins'
  shell       '/bin/false'
  uid         <you wish>
  group       'jenkins'
  action      :create
end

#
# Set the authentication key if we have an authentication user
#
ruby_block 'set_jenkins_private_key' do
  block do
    require 'openssl'
    require 'net/ssh'

    key = OpenSSL::PKey::RSA.new(jenkins_keys[auth_user]['private_key'])
    node.run_state[:jenkins_private_key] = key.to_pem
  end
  action :run
  not_if { auth_user == ''}
end

#
# Set up the slave
#
jenkins_jnlp_slave ipaddress do
  remote_fs '/home/jenkins'
  action [:create, :connect]
  not_if { master == 'localhost' }
```
### Expected Result:

The Jenkins slave gets created and connected and has it's IP address as name.
### Actual Result:

```
       Recipe: chef-vault::default
         * chef_gem[chef-vault] action install (up to date)
       Recipe: mnet_jenkins::slave
         * yum_package[java-1.8.0-openjdk, java-1.8.0-openjdk-headless] action purge
           - purge  package ["java-1.8.0-openjdk", "java-1.8.0-openjdk-headless"]
       Recipe: java::set_java_home
         * ruby_block[set-env-java-home] action run
           - execute the ruby block set-env-java-home
         * directory[/etc/profile.d] action create (up to date)
         * template[/etc/profile.d/jdk.sh] action create
           - create new file /etc/profile.d/jdk.sh
           - update content in file /etc/profile.d/jdk.sh from none to c67dbe
           --- /etc/profile.d/jdk.sh    2016-10-12 10:50:14.444721796 +0200
           +++ /etc/profile.d/.chef-jdk20161012-10854-1o7yjoi.sh        2016-10-12 10:50:14.443721798 +0200
           @@ -1 +1,2 @@
           +export JAVA_HOME=/usr/java/latest
           - change mode from '' to '0755'
           - restore selinux security context
         * ruby_block[Set JAVA_HOME in /etc/environment] action run
           - execute the ruby block Set JAVA_HOME in /etc/environment
       Recipe: java::notify
         * log[jdk-version-changed] action nothing (skipped due to action :nothing)
       Recipe: java::oracle_rpm
         * bash[update-java-alternatives] action nothing (skipped due to action :nothing)
         * yum_package[jdk1.8.0] action install
           - install version 1.8.0-7.el7.centos of package jdk1.8.0
         * bash[update-java-alternatives] action run
           - execute "bash"  "/tmp/chef-script20161012-10854-1yrrl9k"
       Recipe: java::notify
         * log[jdk-version-changed] action write

       Recipe: mnet_jenkins::slave
         * group[jenkins] action create
           - create group jenkins
         * linux_user[jenkins] action create
           - create user jenkins
         * ruby_block[set_jenkins_private_key] action run
           - execute the ruby block set_jenkins_private_key
         * jenkins_jnlp_slave[192.168.211.200] action create
         Recipe: <Dynamically Defined Resource>
           * remote_file[/tmp/kitchen/cache/jenkins-cli.jar] action create
             - create new file /tmp/kitchen/cache/jenkins-cli.jar
             - update content in file /tmp/kitchen/cache/jenkins-cli.jar from none to 0a27bb
             (new content is binary, diff output suppressed)
             - change mode from '' to '0755'
             - restore selinux security context
           * remote_file[/tmp/kitchen/cache/update-center.json] action create
             - create new file /tmp/kitchen/cache/update-center.json
             - update content in file /tmp/kitchen/cache/update-center.json from none to 7e75dc
             - suppressed sensitive resource
             - change mode from '' to '0644'
             - restore selinux security context
           * file[/tmp/kitchen/cache/extracted-update-center.json] action create
             - create new file /tmp/kitchen/cache/extracted-update-center.json
             - update content in file /tmp/kitchen/cache/extracted-update-center.json from none to 39d800
             - suppressed sensitive resource
             - change mode from '' to '0644'
             - restore selinux security context
           * file[/tmp/kitchen/cache/jenkins-key] action create
             - create new file /tmp/kitchen/cache/jenkins-key
             - update content in file /tmp/kitchen/cache/jenkins-key from none to 33300f
             - suppressed sensitive resource
             - change mode from '' to '0600'
             - restore selinux security context

           ================================================================================
           Error executing action `create` on resource 'jenkins_jnlp_slave[192.168.211.200]'
           ================================================================================

           RuntimeError
           ------------
           implicit argument passing of super from method defined by define_method() is not supported. Specify all arguments explicitly.

           Cookbook Trace:
           ---------------
           /tmp/kitchen/cache/cookbooks/jenkins/libraries/slave_jnlp.rb:55:in `block in <class:JenkinsJnlpSlave>'

           Resource Declaration:
           ---------------------
           # In /tmp/kitchen/cache/cookbooks/mnet_jenkins/recipes/slave.rb

            70: jenkins_jnlp_slave ipaddress do
            71:   remote_fs '/home/jenkins'
            72:   action [:create, :connect]
            73:   not_if { master == 'localhost' }
            74: end

           Compiled Resource:
           ------------------
           # Declared in /tmp/kitchen/cache/cookbooks/mnet_jenkins/recipes/slave.rb:70:in `from_file'

           jenkins_jnlp_slave("192.168.211.200") do
             action [:create, :connect]
             retries 0
             retry_delay 2
             default_guard_interpreter :default
             declared_type :jenkins_jnlp_slave
             cookbook_name "mnet_jenkins"
             recipe_name "slave"
             remote_fs "/home/jenkins"
             slave_name "192.168.211.200"
             not_if { #code block }
           end

           Platform:
           ---------
           x86_64-linux
```

Here's the stack.out:

```
Generated at 2016-10-12 10:50:32 +0200
RuntimeError: jenkins_jnlp_slave[192.168.211.200] (mnet_jenkins::slave line 70) had an error: RuntimeError: implicit argument passing of super from method defined by define_method() is not supported. Specify all arguments explicitly.
/tmp/kitchen/cache/cookbooks/jenkins/libraries/slave_jnlp.rb:55:in `block in <class:JenkinsJnlpSlave>'
(eval):2:in `block in action_create'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.14.89/lib/chef/provider.rb:361:in `instance_eval'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.14.89/lib/chef/provider.rb:361:in `compile_and_converge_action'
(eval):2:in `action_create'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.14.89/lib/chef/provider.rb:145:in `run_action'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.14.89/lib/chef/resource.rb:603:in `run_action'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.14.89/lib/chef/runner.rb:69:in `run_action'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.14.89/lib/chef/runner.rb:97:in `block (2 levels) in converge'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.14.89/lib/chef/runner.rb:97:in `each'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.14.89/lib/chef/runner.rb:97:in `block in converge'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.14.89/lib/chef/resource_collection/resource_list.rb:94:in `block in execute_each_resource'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.14.89/lib/chef/resource_collection/stepable_iterator.rb:114:in `call_iterator_block'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.14.89/lib/chef/resource_collection/stepable_iterator.rb:85:in `step'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.14.89/lib/chef/resource_collection/stepable_iterator.rb:103:in `iterate'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.14.89/lib/chef/resource_collection/stepable_iterator.rb:55:in `each_with_index'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.14.89/lib/chef/resource_collection/resource_list.rb:92:in `execute_each_resource'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.14.89/lib/chef/runner.rb:96:in `converge'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.14.89/lib/chef/client.rb:669:in `block in converge'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.14.89/lib/chef/client.rb:664:in `catch'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.14.89/lib/chef/client.rb:664:in `converge'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.14.89/lib/chef/client.rb:703:in `converge_and_save'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.14.89/lib/chef/client.rb:283:in `run'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.14.89/lib/chef/application.rb:302:in `block in fork_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.14.89/lib/chef/application.rb:290:in `fork'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.14.89/lib/chef/application.rb:290:in `fork_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.14.89/lib/chef/application.rb:255:in `block in run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.14.89/lib/chef/local_mode.rb:44:in `with_server_connectivity'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.14.89/lib/chef/application.rb:243:in `run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.14.89/lib/chef/application/client.rb:464:in `sleep_then_run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.14.89/lib/chef/application/client.rb:451:in `block in interval_run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.14.89/lib/chef/application/client.rb:450:in `loop'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.14.89/lib/chef/application/client.rb:450:in `interval_run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.14.89/lib/chef/application/client.rb:434:in `run_application'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.14.89/lib/chef/application.rb:60:in `run'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.14.89/bin/chef-client:26:in `<top (required)>'
/opt/chef/bin/chef-client:54:in `load'
/opt/chef/bin/chef-client:54:in `<main>'

>>>> Caused by RuntimeError: implicit argument passing of super from method defined by define_method() is not supported. Specify all arguments explicitly.
/tmp/kitchen/cache/cookbooks/jenkins/libraries/slave_jnlp.rb:55:in `block in <class:JenkinsJnlpSlave>'
(eval):2:in `block in action_create'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.14.89/lib/chef/provider.rb:361:in `instance_eval'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.14.89/lib/chef/provider.rb:361:in `compile_and_converge_action'
(eval):2:in `action_create'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.14.89/lib/chef/provider.rb:145:in `run_action'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.14.89/lib/chef/resource.rb:603:in `run_action'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.14.89/lib/chef/runner.rb:69:in `run_action'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.14.89/lib/chef/runner.rb:97:in `block (2 levels) in converge'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.14.89/lib/chef/runner.rb:97:in `each'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.14.89/lib/chef/runner.rb:97:in `block in converge'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.14.89/lib/chef/resource_collection/resource_list.rb:94:in `block in execute_each_resource'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.14.89/lib/chef/resource_collection/stepable_iterator.rb:114:in `call_iterator_block'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.14.89/lib/chef/resource_collection/stepable_iterator.rb:85:in `step'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.14.89/lib/chef/resource_collection/stepable_iterator.rb:103:in `iterate'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.14.89/lib/chef/resource_collection/stepable_iterator.rb:55:in `each_with_index'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.14.89/lib/chef/resource_collection/resource_list.rb:92:in `execute_each_resource'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.14.89/lib/chef/runner.rb:96:in `converge'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.14.89/lib/chef/client.rb:669:in `block in converge'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.14.89/lib/chef/client.rb:664:in `catch'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.14.89/lib/chef/client.rb:664:in `converge'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.14.89/lib/chef/client.rb:703:in `converge_and_save'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.14.89/lib/chef/client.rb:283:in `run'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.14.89/lib/chef/application.rb:302:in `block in fork_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.14.89/lib/chef/application.rb:290:in `fork'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.14.89/lib/chef/application.rb:290:in `fork_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.14.89/lib/chef/application.rb:255:in `block in run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.14.89/lib/chef/local_mode.rb:44:in `with_server_connectivity'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.14.89/lib/chef/application.rb:243:in `run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.14.89/lib/chef/application/client.rb:464:in `sleep_then_run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.14.89/lib/chef/application/client.rb:451:in `block in interval_run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.14.89/lib/chef/application/client.rb:450:in `loop'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.14.89/lib/chef/application/client.rb:450:in `interval_run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.14.89/lib/chef/application/client.rb:434:in `run_application'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.14.89/lib/chef/application.rb:60:in `run'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.14.89/bin/chef-client:26:in `<top (required)>'
/opt/chef/bin/chef-client:54:in `load'
/opt/chef/bin/chef-client:54:in `<main>'[chefinit@centos7 
```

**Comment by lamont-granquist** [comment]
i think i actually just fixed this in #523

**Comment by iennae** [comment]
Please verify that this problem is resolved with version 3.1.1 of this cookbook. Reopen if this is still a problem. Thank you!

**Comment by jmaass** [comment]
Hi iennae,

when i use the same code with v3.1.1 of the jenkins cookbook, I get the following error:

```
         * jenkins_jnlp_slave[192.168.211.241] action create
         Recipe: <Dynamically Defined Resource>
           * remote_file[/tmp/kitchen/cache/jenkins-cli.jar] action create
             - create new file /tmp/kitchen/cache/jenkins-cli.jar
             - update content in file /tmp/kitchen/cache/jenkins-cli.jar from none to 64ef26
             (new content is binary, diff output suppressed)
             - change mode from '' to '0755'
             - restore selinux security context
           * remote_file[/tmp/kitchen/cache/update-center.json] action create
             - create new file /tmp/kitchen/cache/update-center.json
             - update content in file /tmp/kitchen/cache/update-center.json from none to 59f911
             - suppressed sensitive resource
             - change mode from '' to '0644'
             - restore selinux security context
           * file[/tmp/kitchen/cache/extracted-update-center.json] action create
             - create new file /tmp/kitchen/cache/extracted-update-center.json
             - update content in file /tmp/kitchen/cache/extracted-update-center.json from none to 771305
             - suppressed sensitive resource
             - change mode from '' to '0644'
             - restore selinux security context
           * file[/tmp/kitchen/cache/jenkins-key] action create
             - create new file /tmp/kitchen/cache/jenkins-key
             - update content in file /tmp/kitchen/cache/jenkins-key from none to 33300f
             - suppressed sensitive resource
             - change mode from '' to '0600'
             - restore selinux security context
           - Create jenkins_jnlp_slave[192.168.211.241]
           * directory[/home/jenkins] action create
             - create new directory /home/jenkins
             - restore selinux security context
           * group[jenkins] action create (up to date)
           * user_resource_abstract_base_class[jenkins] action create[2016-10-18T17:20:34+02:00] WARN: Class Chef::Provider::User does not declare 'provides :user'.
       [2016-10-18T17:20:34+02:00] WARN: This will no longer work in Chef 13: you must use 'provides' to use the resource's DSL.
       
             
             ================================================================================
             Error executing action `create` on resource 'user_resource_abstract_base_class[jenkins]'
             ================================================================================
             
             NotImplementedError
             -------------------
             NotImplementedError
             
             Cookbook Trace:
             ---------------
             /tmp/kitchen/cache/cookbooks/jenkins/libraries/slave_jnlp.rb:61:in `block in <class:JenkinsJnlpSlave>'
             
             Compiled Resource:
             ------------------
             # Declared in 
             
             user_resource_abstract_base_class("jenkins") do
        action [:create]
        supports {:manage_home=>false, :non_unique=>false}
        retries 0
        retry_delay 2
        default_guard_interpreter :default
        username "jenkins"
        comment "Jenkins slave user - Created by Chef"
        gid 11119
        home "/home/jenkins"
        iterations 27855
             end
             
             Platform:
             ---------
             x86_64-linux
             
           
           ================================================================================
           Error executing action `create` on resource 'jenkins_jnlp_slave[192.168.211.241]'
           ================================================================================
           
           NotImplementedError
           -------------------
           user_resource_abstract_base_class[jenkins] (dynamically defined) had an error: NotImplementedError: NotImplementedError
           
           Cookbook Trace:
           ---------------
           /tmp/kitchen/cache/cookbooks/jenkins/libraries/slave_jnlp.rb:61:in `block in <class:JenkinsJnlpSlave>'
           
           Resource Declaration:
           ---------------------
           # In /tmp/kitchen/cache/cookbooks/mnet_jenkins/recipes/slave.rb
           
            70: jenkins_jnlp_slave ipaddress do
            71:   remote_fs '/home/jenkins'
            72:   action [:create, :connect]
            73:   not_if { master == 'localhost' }
            74: end
           
           Compiled Resource:
           ------------------
           # Declared in /tmp/kitchen/cache/cookbooks/mnet_jenkins/recipes/slave.rb:70:in `from_file'
           
           jenkins_jnlp_slave("192.168.211.241") do
             action [:create, :connect]
             retries 0
             retry_delay 2
             default_guard_interpreter :default
             declared_type :jenkins_jnlp_slave
             cookbook_name "mnet_jenkins"
             recipe_name "slave"
             remote_fs "/home/jenkins"
             slave_name "192.168.211.241"
             usage_mode "normal"
             description "Jenkins slave 192.168.211.241"
             group "jenkins"
             user "jenkins"
             not_if { #code block }
           end
           
           Platform:
           ---------
           x86_64-linux
           
       Recipe: chef-client::systemd_service
         * service[chef-client] action restart
           - restart service service[chef-client]
       Recipe: misc::hosts_entry
         * service[network] action restart
           - restart service service[network]
       
       Running handlers:
       [2016-10-18T17:20:37+02:00] ERROR: Running exception handlers
       Running handlers complete
       [2016-10-18T17:20:37+02:00] ERROR: Exception handlers complete
       Chef Client failed. 54 resources updated in 43 seconds
       [2016-10-18T17:20:37+02:00] FATAL: Stacktrace dumped to /tmp/kitchen/cache/chef-stacktrace.out
       [2016-10-18T17:20:37+02:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
       [2016-10-18T17:20:37+02:00] ERROR: jenkins_jnlp_slave[192.168.211.241] (mnet_jenkins::slave line 70) had an error: NotImplementedError: user_resource_abstract_base_class[jenkins] (dynamically defined) had an error: NotImplementedError: NotImplementedError
       [2016-10-18T17:20:37+02:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
```

**Comment by iennae** [comment]
I think this is the original error you reported which I'm still working on fixing. You are no longer getting the error:

           RuntimeError
           ------------
           implicit argument passing of super from method defined by define_method() is not supported. Specify all arguments explicitly.

Correct?

**Comment by jmaass** [comment]
Dear Jennifer,

correct if I use the latest version of the jenkins cookbook. However, slave converge still fails with a different error, but I’ve already opened a ticket for that.

Mit freundlichen Grüßen/Kind regards

Jörg Maaß
Hays AG
Release Management Retail im Bereich IT
--
M-net Telekommunikations GmbH
Emmy-Noether-Str. 2 | 80992 München

Tel. 089 45200 8356 | Fax 089 45200 708356 | Mobil 0178 5352364
www.m-net.de<http://www.m-net.de/> | joerg.maass.ext@m-net.de<mailto:joerg.maass.ext@m-net.de>
M-net auf Facebook<http://www.facebook.com/Mnet.MeinNetz> | YouTube<http://www.youtube.com/user/MnetMeinNetz> | XING<http://www.xing.com/company/m-net>
Sitz München – Amtsgericht München HRB 108514
Geschäftsführer: Jens Prautzsch (Vorsitzender) | Simone Büber-Monath | Michael Fränkle
Vorsitzende des Aufsichtsrats: Erna-Maria Trixl
[M-net_Testsieger]

Von: Jennifer Davis [mailto:notifications@github.com]
Gesendet: Mittwoch, 19. Oktober 2016 07:49
An: chef-cookbooks/jenkins
Cc: Maaß.Jörg; Author
Betreff: Re: [chef-cookbooks/jenkins] Error "implicit argument passing of super from method defined by define_method() is not supported." when using jenkins_slave (#524)


I think this is the original error you reported which I'm still working on fixing. You are no longer getting the error:

       RuntimeError

       ------------

       implicit argument passing of super from method defined by define_method() is not supported. Specify all arguments explicitly.

Correct?

**Comment by iennae** [comment]
Great, yeah just wanted to make sure this particular issue is resolved. Thanks!
