### ISSUE TITLE
jenkins_script: NoMethodError: undefined method `+' for nil:NilClass

### ISSUE THREAD

**Issue by lioramilbaum** [sous-chefs/jenkins#667]
### Cookbook version
5.0.5

### Chef-client version
13.6.4

### Platform Details
AWS - Ubuntu 16.04

### Scenario:
Recipe with jenkins_script resource fails

### Steps to Reproduce:
Recipe:

```jenkins_script 'println("This is Groovy code!")'```

### Actual Result:
```
ec2-54-76-216-204.eu-west-1.compute.amazonaws.com Recipe: depy-jenkins::master
ec2-54-76-216-204.eu-west-1.compute.amazonaws.com   * jenkins_script[println("This is Groovy code!")] action execute
ec2-54-76-216-204.eu-west-1.compute.amazonaws.com     
ec2-54-76-216-204.eu-west-1.compute.amazonaws.com     ================================================================================
ec2-54-76-216-204.eu-west-1.compute.amazonaws.com     Error executing action `execute` on resource 'jenkins_script[println("This is Groovy code!")]'
ec2-54-76-216-204.eu-west-1.compute.amazonaws.com     ================================================================================
ec2-54-76-216-204.eu-west-1.compute.amazonaws.com     
ec2-54-76-216-204.eu-west-1.compute.amazonaws.com     NoMethodError
ec2-54-76-216-204.eu-west-1.compute.amazonaws.com     -------------
ec2-54-76-216-204.eu-west-1.compute.amazonaws.com     undefined method `+' for nil:NilClass
ec2-54-76-216-204.eu-west-1.compute.amazonaws.com     
ec2-54-76-216-204.eu-west-1.compute.amazonaws.com     Cookbook Trace:
ec2-54-76-216-204.eu-west-1.compute.amazonaws.com     ---------------
ec2-54-76-216-204.eu-west-1.compute.amazonaws.com     /var/chef/cache/cookbooks/jenkins/libraries/_helper.rb:428:in `block in wait_until_ready!'
ec2-54-76-216-204.eu-west-1.compute.amazonaws.com     /var/chef/cache/cookbooks/jenkins/libraries/_helper.rb:426:in `wait_until_ready!'
ec2-54-76-216-204.eu-west-1.compute.amazonaws.com     /var/chef/cache/cookbooks/jenkins/libraries/_helper.rb:61:in `executor'
ec2-54-76-216-204.eu-west-1.compute.amazonaws.com     /var/chef/cache/cookbooks/jenkins/libraries/script.rb:53:in `block (2 levels) in <class:JenkinsScript>'
ec2-54-76-216-204.eu-west-1.compute.amazonaws.com     /var/chef/cache/cookbooks/jenkins/libraries/script.rb:52:in `block in <class:JenkinsScript>'
ec2-54-76-216-204.eu-west-1.compute.amazonaws.com     
ec2-54-76-216-204.eu-west-1.compute.amazonaws.com     Resource Declaration:
ec2-54-76-216-204.eu-west-1.compute.amazonaws.com     ---------------------
ec2-54-76-216-204.eu-west-1.compute.amazonaws.com     # In /var/chef/cache/cookbooks/depy-jenkins/recipes/master.rb
ec2-54-76-216-204.eu-west-1.compute.amazonaws.com     
ec2-54-76-216-204.eu-west-1.compute.amazonaws.com      11: jenkins_script 'println("This is Groovy code!")'
ec2-54-76-216-204.eu-west-1.compute.amazonaws.com     
ec2-54-76-216-204.eu-west-1.compute.amazonaws.com     Compiled Resource:
ec2-54-76-216-204.eu-west-1.compute.amazonaws.com     ------------------
ec2-54-76-216-204.eu-west-1.compute.amazonaws.com     # Declared in /var/chef/cache/cookbooks/depy-jenkins/recipes/master.rb:11:in `from_file'
ec2-54-76-216-204.eu-west-1.compute.amazonaws.com     
ec2-54-76-216-204.eu-west-1.compute.amazonaws.com     jenkins_script("println("This is Groovy code!")") do
ec2-54-76-216-204.eu-west-1.compute.amazonaws.com       action [:execute]
ec2-54-76-216-204.eu-west-1.compute.amazonaws.com       default_guard_interpreter :default
ec2-54-76-216-204.eu-west-1.compute.amazonaws.com       declared_type :jenkins_script
ec2-54-76-216-204.eu-west-1.compute.amazonaws.com       cookbook_name "depy-jenkins"
ec2-54-76-216-204.eu-west-1.compute.amazonaws.com       recipe_name "master"
ec2-54-76-216-204.eu-west-1.compute.amazonaws.com       command "println(\"This is Groovy code!\")"
ec2-54-76-216-204.eu-west-1.compute.amazonaws.com     end
ec2-54-76-216-204.eu-west-1.compute.amazonaws.com     
ec2-54-76-216-204.eu-west-1.compute.amazonaws.com     System Info:
ec2-54-76-216-204.eu-west-1.compute.amazonaws.com     ------------
ec2-54-76-216-204.eu-west-1.compute.amazonaws.com     chef_version=13.6.4
ec2-54-76-216-204.eu-west-1.compute.amazonaws.com     platform=ubuntu
ec2-54-76-216-204.eu-west-1.compute.amazonaws.com     platform_version=16.04
ec2-54-76-216-204.eu-west-1.compute.amazonaws.com     ruby=ruby 2.4.2p198 (2017-09-14 revision 59899) [x86_64-linux]
ec2-54-76-216-204.eu-west-1.compute.amazonaws.com     program_name=chef-client worker: ppid=28529;start=23:55:51;
ec2-54-76-216-204.eu-west-1.compute.amazonaws.com     executable=/opt/chef/bin/chef-client
ec2-54-76-216-204.eu-west-1.compute.amazonaws.com     
ec2-54-76-216-204.eu-west-1.compute.amazonaws.com 
ec2-54-76-216-204.eu-west-1.compute.amazonaws.com Running handlers:
ec2-54-76-216-204.eu-west-1.compute.amazonaws.com [2017-12-13T23:56:02+02:00] ERROR: Running exception handlers
ec2-54-76-216-204.eu-west-1.compute.amazonaws.com Running handlers complete
ec2-54-76-216-204.eu-west-1.compute.amazonaws.com [2017-12-13T23:56:02+02:00] ERROR: Exception handlers complete
ec2-54-76-216-204.eu-west-1.compute.amazonaws.com Chef Client failed. 0 resources updated in 11 seconds
ec2-54-76-216-204.eu-west-1.compute.amazonaws.com [2017-12-13T23:56:03+02:00] FATAL: Stacktrace dumped to /var/chef/cache/chef-stacktrace.out
ec2-54-76-216-204.eu-west-1.compute.amazonaws.com [2017-12-13T23:56:03+02:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
ec2-54-76-216-204.eu-west-1.compute.amazonaws.com [2017-12-13T23:56:03+02:00] ERROR: jenkins_script[println("This is Groovy code!")] (depy-jenkins::master line 11) had an error: NoMethodError: undefined method `+' for nil:NilClass
ec2-54-76-216-204.eu-west-1.compute.amazonaws.com [2017-12-13T23:56:03+02:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
```

**Comment by lioramilbaum** [comment]
The problem is with node['jenkins']['master']['endpoint'] is not resolved correctly because the host or/and port attributes are not picked up from the attributes.rb file.
After adding those attributes to my role file, it works perfectly.
